[package]
name = "gtktest"
version = "0.1.0"
edition = "2024"

[dependencies]
futures-util = "0.3.31"
relm4 = "0.9.1"
relm4-components = "0.9.1"
relm4-macros = "0.9.1"
reqwest = { version = "0.12.22", features = ["json"] }
tokio = { version = "1.47.1", features = ["time", "fs"] }
